GET http://localhost:3000/api/user HTTP/1.1

###

GET http://localhost:3000/api/user?email=nyberg112@gmail.com HTTP/1.1

###

POST http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
    "name": "DingDong",
    "email": "Ding@gmail.com"
}

###

PUT http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
    "id": "clcjeog670000kw0875rr9lx3",
    "goal": "1500",
    "intake": "1500"
}

###

POST http://localhost:3000/api/history HTTP/1.1
content-type: application/json

{
    "email": "nyberg112@gmail.com",
    "goal": "1200",
    "intake": "1500",
    "today": "4",
    "day": "2",
    "month": "3"
}

###

curl --request POST \
     --url 'http://localhost:3000/api/cron' \
     --header 'Authorization: Bearer p4BzzpE3WXgjriSzgaDtbQMYx'

###

curl --request DELETE \
     --url 'http://localhost:3000/api/cronhistory' \
     --header 'Authorization: Bearer p4BzzpE3WXgjriSzgaDtbQMYx'