import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { getSession, signIn } from "next-auth/react";
import { GetServerSideProps, NextPage } from "next";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  if (session && session.user?.name) {
    return {
      redirect: {
        destination: "/userboard",
        permanent: false,
      },
    }
  }

  else if (session && !session.user?.name) {
    return {
      redirect: {
        destination: "/goal",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>H2GO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-192x192.png" />
      </Head>
      <main>
        <div>
          <div>
            <span>Logo</span>
            <p>Stay hydrated</p>
          </div>
          <h2>Water is natures powerup</h2>
          <h3>
            The right amount of water have magical effect on your health, start
            measuring now
          </h3>
          <div>
            <button onClick={() => signIn()}>Start your journey</button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
